version: '3.12'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
      - --port ${REDIS_PORT}
    env_file:
      - .env
    restart: on-failure
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  db:
    image: mysql:8
    env_file:
      - .env
    volumes:
       - my-db:/var/lib/mysql
    restart: on-failure
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
  bot:
    build: .
    command: sh -c "alembic upgrade head && python -m run"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
      - redis

volumes:
  my-db: